$lock_wall = $HOME/.config/hypr/custom/lockscreen-wallpaper

# BACKGROUND
background {
    monitor =
    path = $lock_wall

    blur_passes = 1
    blur_size = 4

    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    grace = 0
    disable_loading_bar = false
}

# LEFT GLASS PANEL
shape {
    monitor =
    size = 650, 100%

    color = rgba(20, 24, 32, 0.45)

    rounding = 0
    border_size = 0

    position = 0, 0
    halign = left
    valign = center
}

# GREETINGS
label {
    monitor =
    text = <span allow_breaks="true">Welcome back,<br/>I guess.</span>

    color = rgba(205, 214, 224, .75)

    font_size = 44
    text_align = left
    font_family = JetBrainsMono Nerd Font

    position = 135, 340
    halign = left
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"

    color = rgba(205, 214, 224, .75)

    font_size = 40
    text_align = left
    font_family = JetBrainsMono Nerd Font

    position = 230, 195
    halign = left
    valign = center
}

# DATE
label {
    monitor =
    text = Sunday, September 29

    color = rgba(205, 214, 224, .75)

    font_size = 20
    text_align = left
    font_family = JetBrainsMono Nerd Font

    position = 165, 145
    halign = left
    valign = center
}

# PROFILE PHOTO
image {
    monitor =
    path = ~/.config/hypr/pfp.webp

    border_size = 1
    border_color = rgba(137, 180, 250, .75)

    size = 160
    rounding = -1

    position = 245, 10
    halign = left
    valign = center
}

# USER BOX
shape {
    monitor =

    size = 350, 55

    color = rgba(255, 255, 255, .20)

    rounding = -1
    border_size = 0

    position = 140, -135
    halign = left
    valign = center
}

# USER LABEL
label {
    monitor =
    text =   $USER

    color = rgba(205, 214, 224, 0.80)

    font_size = 16
    text_align = left
    font_family = JetBrainsMono Nerd Font

    position = 255, -135
    halign = left
    valign = center
}

# INPUT FIELD
input-field {
    monitor =

    size = 350, 55

    outline_thickness = 0

    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.10)

    font_color = rgb(205, 214, 244)

    fade_on_empty = false
    hide_input = false

    font_family = JetBrainsMono Nerd Font

    placeholder_text = <i><span foreground="##ffffff99">Prove it.</span></i>

    position = 140, -210
    halign = left
    valign = center
}

# STATUS MESSAGE
label {
    monitor =
    text = The machine remains unconvinced.

    color = rgba(205, 214, 224, 0.75)

    font_size = 12
    text_align = left
    font_family = JetBrainsMono Nerd Font

    position = 160, -260
    halign = left
    valign = center
}

# AUTH
auth {
    pam:enabled = true
    pam:module = hyprlock

    fingerprint:enabled = true
    fingerprint:ready_message = Scan fingerprint to unlock
    fingerprint:present_message = Scanning fingerprint
    fingerprint:retry_delay = 100
}

# BATTERY STATUS
label {
    monitor =
    text = cmd[update:5000] ~/.config/hypr/hyprlock/status.sh

    color = rgba(205, 214, 224, 0.55)

    font_size = 11
    text_align = left
    font_family = JetBrainsMono Nerd Font

    position = 240, 30
    halign = left
    valign = bottom
}

# CAPS LOCK WARNING
label {
    monitor =
    text = cmd[update:250] ~/.config/hypr/hyprlock/check-capslock.sh

    color = rgba(255, 180, 180, 0.90)

    font_size = 14
    text_align = left
    font_family = JetBrainsMono Nerd Font

    position = 140, -250
    halign = left
    valign = center
}
